services:
  postgres:
    container_name: zeenchat_postgres
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: zeenchat
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
    ports:
      - 5432:5432

volumes:
  postgres_data:
